<div class="ma-block-group">
	<div class="block-group">
		<div class="container">
			<?php  echo $this->getLayout()->createBlock('bestsellerproductslider/bestsellerproductslider')->setTemplate('magentothem/bestsellerproductslider/bestsellerproductslider.phtml')->toHtml(); ?>
		</div>
	</div>
</div>
<div class="blog-slider">
	<div class="container">
		<div class="container-inner">
			<?php  echo $this->getLayout()->createBlock('blog/menu_sidebar')->setTemplate('magentothem_blog/blog_slide.phtml')->toHtml(); ?>
		</div>
	</div>
</div>
<div class="brand-slider">
	<div class="container">
		<div class="container-inner">
			<?php // echo $this->getLayout()->createBlock('brandslider/brandslider')->setTemplate('magentothem/brandslider/brandslider.phtml')->toHtml(); ?>
		</div>
	</div>
</div>
