<?php if($this->getConfig('enabled') == 1):?>
	<?php
		$auto = $this->getConfig('auto');
		$speed = $this->getConfig('speed');
		$next_back = $this->getConfig('next_back');
		$nav_ctrl = $this->getConfig('nav_ctrl');
		$rows = 1;
		$i = 0;
	?>
	<div class="block block-testimonial-sidebar">			
		<?php $latestTestimonial = $this->getTestimonialsLast()?>
		<?php if(count($latestTestimonial) > 0):?>
			<div class="block-title">
				<strong><span><?php echo $this->__('Latest Testimonials')?></span></strong>
			</div>
			<div class="block-content">
				<div class="container">
				<div class="row">
				<ul class="owl">			
					<?php foreach($latestTestimonial as $_item):?>
						<?php if($i % $rows == 0) echo "<li class='testimonial-list'>"; ?>								
							<div class="testimonial-sidebar-content">
							<div class="content">
							<div class="testimonial-content-avatar">
								<?php
									if($_item->getAvatar() != ''){
										$avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .$_item->getAvatar();
										?><img src="<?php echo $avatarLink ?>" alt="test" height="120" width="120" /><?php
									}
								?>
							</div>	
							<div class="post-by">	
								<div class="testimonial-top">
								<span class="testimonial-author"><?php echo $_item->getName(); ?></span>							
								<span class="testimonial-date"><?php echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($_item->getCreatedTime())); ?></span>
								</div>
								<a href="<?php echo $this->getUrl('testimonial')?>">						    
									<?php									
										$_description = $_item->getTestimonial();									
										//$short_desc = $this->getContentTestimonialSidebar($_description, 100);									
										echo $_description;	 ?>						   
								</a>		
								
							</div>														
							</div>
							</div>
							<?php $i++;?>
						<?php if($i %$rows == 0) echo "</li>"; ?>                    
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>		
				</ul>
				</div>
			</div>
			</div>	
		<?php endif ?>	
	</div>
	<script type="text/javascript">
		// $jq(document).ready(function(){
			$jq(".block-testimonial-sidebar .owl").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : 1,
				itemsDesktop : [1199,1],
				itemsDesktopSmall : [980,1],
				itemsTablet: [768,1],
				itemsMobile : [479,1],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true,
			});
			var owlslider = $jq(".block-testimonial-sidebar .owl").data('owlCarousel');
		// });
		
		
	</script>
<?php endif ?>