<?php
$_image_w = Mage::getStoreConfig('quickview/media_config/width_main_image');
$_image_h= Mage::getStoreConfig('quickview/media_config/height_main_image');
$_thumbnail_w = Mage::getStoreConfig('quickview/media_config/width_thumbnail');
$_thumbnail_h = Mage::getStoreConfig('quickview/media_config/height_thumbnail');
$auto = Mage::getStoreConfig('quickview/media_config/auto');
$speed = Mage::getStoreConfig('quickview/media_config/speed');
$itemsDefault = Mage::getStoreConfig('quickview/media_config/itemsDefault');
$itemsDesktop = Mage::getStoreConfig('quickview/media_config/itemsDesktop');
$itemsDesktopSmall = Mage::getStoreConfig('quickview/media_config/itemsDesktopSmall');
$itemsTablet = Mage::getStoreConfig('quickview/media_config/itemsTablet');
$itemsMobile = Mage::getStoreConfig('quickview/media_config/itemsMobile');
$next_back = Mage::getStoreConfig('quickview/media_config/next_back');
$nav_ctrl = Mage::getStoreConfig('quickview/media_config/nav_ctrl');
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<p class="product-image">
    <img id="image-main" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_image_w,$_image_h); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()); ?>" title="<?php echo $this->htmlEscape($this->getImageLabel()); ?>" />
</p>
<?php if ( count($this->getGalleryImages()) > 0 ): ?>
    <div class="more-views ma-thumbnail-container">
        <h2><?php echo $this->__('More Views') ?></h2>
        <ul class="bxslider">
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <li class="thumbnail-item">
                    <a href="javascript:void(0);" class="thumb-link" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_image_w, $_image_h); ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbnail_w, $_thumbnail_h); ?>" width="<?php echo $_thumbnail_w ?>" height="<?php echo $_thumbnail_h ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[

    $jq(".ma-thumbnail-container .bxslider").bxSlider({
							<?php if($_auto ) { ?>
								auto: true,
							<?php } ?>
							slideWidth: <?php echo $_thumbnail_w ?>,
							slideMargin: 12,
							minSlides: 4,
							maxSlides: 4,
							<?php if (count($this->getGalleryImages()) < 5 ) { ?>
							controls: false,
							<?php } ?>
							pager: false,
							speed: 500,
							pause: 3000,
							mode: 'vertical',
							adaptiveHeight: true
						});		

    $jq('#image-main').elevateZoom();
    $jq('.thumb-link').click(function() {
        $jq('.zoomContainer').remove();
        var imgUrl = $jq(this).data('image');
        $jq('#image-main').attr('src', imgUrl).elevateZoom();
    });
//]]>
</script>
